#include "CodeGenTables.h"

namespace lethe
{

const Int opcodeRefLoadOfs[DT_FUNC_PTR+1] =
{
	OPC_HALT, OPC_PLOAD8U, OPC_PLOAD8U, OPC_PLOAD8, OPC_PLOAD16, OPC_PLOAD16U,
	OPC_PLOAD32, OPC_PLOAD32, OPC_PLOAD32, OPC_PLOAD32, OPC_PLOAD64, OPC_PLOAD64,
	OPC_PLOAD32F, OPC_PLOAD64D, OPC_PLOAD64, OPC_PLOADPTR, OPC_PLOADPTR
};

const Int opcodeGlobalLoad[DT_FUNC_PTR + 1] =
{
	OPC_HALT, OPC_GLOAD8U, OPC_GLOAD8U, OPC_GLOAD8, OPC_GLOAD16, OPC_GLOAD16U,
	OPC_GLOAD32, OPC_GLOAD32, OPC_GLOAD32, OPC_GLOAD32, OPC_GLOAD64, OPC_GLOAD64,
	OPC_GLOAD32F, OPC_GLOAD64D, OPC_GLOAD64, OPC_GLOADPTR, OPC_GLOADPTR
};

const Int opcodeLocalLoad[DT_FUNC_PTR + 1] =
{
	OPC_HALT, OPC_LPUSH8U, OPC_LPUSH8U, OPC_LPUSH8, OPC_LPUSH16, OPC_LPUSH16U,
	OPC_LPUSH32, OPC_LPUSH32, OPC_LPUSH32, OPC_LPUSH32, OPC_LPUSH64, OPC_LPUSH64,
	OPC_LPUSH32F, OPC_LPUSH64D, OPC_LPUSH64, OPC_LPUSHPTR, OPC_LPUSHPTR
};

const Int opcodeLocalStore[2][DT_FUNC_PTR + 1] =
{
	{
		OPC_HALT, OPC_LSTORE8, OPC_LSTORE8, OPC_LSTORE8, OPC_LSTORE16, OPC_LSTORE16,
		OPC_LSTORE32, OPC_LSTORE32, OPC_LSTORE32, OPC_LSTORE32, OPC_LSTORE64, OPC_LSTORE64,
		OPC_LSTORE32F, OPC_LSTORE64D, OPC_LSTORE64, OPC_LSTOREPTR, OPC_LSTOREPTR
	},
	{
		OPC_HALT, OPC_LSTORE8_NP, OPC_LSTORE8_NP, OPC_LSTORE8_NP, OPC_LSTORE16_NP, OPC_LSTORE16_NP,
		OPC_LSTORE32_NP, OPC_LSTORE32_NP, OPC_LSTORE32_NP, OPC_LSTORE32_NP, OPC_LSTORE64_NP, OPC_LSTORE64_NP,
		OPC_LSTORE32F_NP, OPC_LSTORE64D_NP, OPC_LSTORE64_NP, OPC_LSTOREPTR_NP, OPC_LSTOREPTR_NP
	}
};

const Int opcodeGlobalStore[2][DT_FUNC_PTR + 1] =
{
	{
		OPC_HALT, OPC_GSTORE8, OPC_GSTORE8, OPC_GSTORE8, OPC_GSTORE16, OPC_GSTORE16,
		OPC_GSTORE32, OPC_GSTORE32, OPC_GSTORE32, OPC_GSTORE32, OPC_GSTORE64, OPC_GSTORE64,
		OPC_GSTORE32F, OPC_GSTORE64D, OPC_GSTORE64, OPC_GSTOREPTR, OPC_GSTOREPTR
	},
	{
		OPC_HALT, OPC_GSTORE8_NP, OPC_GSTORE8_NP, OPC_GSTORE8_NP, OPC_GSTORE16_NP, OPC_GSTORE16_NP,
		OPC_GSTORE32_NP, OPC_GSTORE32_NP, OPC_GSTORE32_NP, OPC_GSTORE32_NP, OPC_GSTORE64_NP, OPC_GSTORE64_NP,
		OPC_GSTORE32F_NP, OPC_GSTORE64D_NP, OPC_GSTORE64_NP, OPC_GSTOREPTR_NP, OPC_GSTOREPTR_NP
	}
};

const Int opcodeRefStore[2][DT_FUNC_PTR + 1] =
{
	{
		OPC_HALT, OPC_PSTORE8_IMM, OPC_PSTORE8_IMM, OPC_PSTORE8_IMM, OPC_PSTORE16_IMM, OPC_PSTORE16_IMM,
		OPC_PSTORE32_IMM, OPC_PSTORE32_IMM, OPC_PSTORE32_IMM, OPC_PSTORE32_IMM, OPC_PSTORE64_IMM0, OPC_PSTORE64_IMM0,
		OPC_PSTORE32F_IMM, OPC_PSTORE64D_IMM, OPC_PSTORE64_IMM0, OPC_PSTOREPTR_IMM, OPC_PSTOREPTR_IMM
	},
	{
		OPC_HALT, OPC_PSTORE8_IMM_NP, OPC_PSTORE8_IMM_NP, OPC_PSTORE8_IMM_NP, OPC_PSTORE16_IMM_NP, OPC_PSTORE16_IMM_NP,
		OPC_PSTORE32_IMM_NP, OPC_PSTORE32_IMM_NP,
		OPC_PSTORE32_IMM_NP, OPC_PSTORE32_IMM_NP,
		OPC_PSTORE64_IMM0_NP, OPC_PSTORE64_IMM0_NP,
		OPC_PSTORE32F_IMM_NP, OPC_PSTORE64D_IMM_NP, OPC_PSTORE64_IMM0_NP, OPC_PSTOREPTR_IMM_NP,
		OPC_PSTOREPTR_IMM_NP
	}
};

const Int opcodeRefInc[DT_NAME] =
{
	OPC_HALT, OPC_HALT, OPC_PINC8U, OPC_PINC8, OPC_PINC16, OPC_PINC16U,
	OPC_PINC32, OPC_PINC32, OPC_PINC32, OPC_PINC32, OPC_PINC64, OPC_PINC64,
	OPC_PINC32F, OPC_PINC64D
};

const Int opcodeRefIncPost[DT_NAME] =
{
	OPC_HALT, OPC_HALT, OPC_PINC8U_POST, OPC_PINC8_POST, OPC_PINC16_POST, OPC_PINC16U_POST,
	OPC_PINC32_POST, OPC_PINC32_POST, OPC_PINC32_POST, OPC_PINC32_POST, OPC_PINC64_POST, OPC_PINC64_POST,
	OPC_PINC32F_POST, OPC_PINC64D_POST
};

}
